language: python
python:
  - "3.6"

env:
  global:
    - CIBW_BEFORE_BUILD='bash build-deps.sh'
    - CIBW_SKIP='cp27-* cp33-* cp34-* cp35-* cp37-*'
    - CIBW_BUILD_VERBOSITY=3
    - CIBW_ENVIRONMENT='CFLAGS="-std=c99"'
    - CIBW_TEST_COMMAND='pytest {project}/'
    - CIBW_TEST_REQUIRES='pytest'

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    # - os: osx
    #   language: generic
    #   env: PIP=pip

install:
  - $PIP install cibuildwheel==0.9.4
  - wget https://files.pythonhosted.org/packages/source/m/mpdaf/mpdaf-2.5.1.tar.gz

script:
  # - export PKG_CONFIG_PATH=cfitsio
  - tar xf mpdaf-2.5.1.tar.gz
  - cd mpdaf-2.5.1
  - cp ../build-deps.sh .
  - cibuildwheel --output-dir ../wheelhouse
  - cd ..
  - ls wheelhouse
